### PR TITLE
Automatically run on install

### PR DESCRIPTION
**Pull request by hello-smile6**
Now, `npm i ScolderCreations/spark` will automatically install and open the browser. Also, the browser will open automatically upon install.

### CODE REVIEW

**Comment by hello-smile6** [comment]
To test:
```bash
npm i hello-smile6/spark#add-autorun
```

**Comment by hello-smile6** [comment]
It works. As soon as I installed it, the browser opened. That way, people can quickly open it.

**Comment by hello-smile6** [comment]
It stopped here and opened the browser.
```
$ npm i hello-smile6/spark#add-autorun
[#########.........] \ reify:spark: sill audit bulk request { spark: [ '1.0.0' ] }
```

**Comment by ScolderCreations** [comment]
> It stopped here and opened the browser.
> 
> ```
> $ npm i hello-smile6/spark#add-autorun
> [#########.........] \ reify:spark: sill audit bulk request { spark: [ '1.0.0' ] }
> ```

Is that intentional? I think not.

**Comment by hello-smile6** [comment]
> > It stopped here and opened the browser.
> > ```
> > $ npm i hello-smile6/spark#add-autorun
> > [#########.........] \ reify:spark: sill audit bulk request { spark: [ '1.0.0' ] }
> > ```
> 
> Is that intentional? I think not.

It does it in the middle of installing. I know how to fix it.

**Comment by ScolderCreations** [comment]
Thanks for adding forge. Can i merge this yet?

**Comment by hello-smile6** [comment]
> Thanks for adding forge. Can i merge this yet?

Still testing

**Comment by hello-smile6** [comment]
Done, ready to merge

**Comment by ScolderCreations** [comment]
This was merged, and immediately there are 13 security vulnerabilities.

**Pull request merged**
